# Generated by Django 6.0.4 on 2026-04-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('subject', models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics'), ('math', 'Mathematics'), ('biology', 'Biology')], max_length=20)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
