"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _landing_hero from './landing-hero.bones.json'
import _landing_simulations from './landing-simulations.bones.json'
import _landing_stats from './landing-stats.bones.json'
import _labzero_main from './labzero-main.bones.json'
import _landing_cards from './landing-cards.bones.json'
import _landing_theory from './landing-theory.bones.json'
import _landing_footer from './landing-footer.bones.json'
import _auth_overlay from './auth-overlay.bones.json'

registerBones({
  "landing-hero": _landing_hero,
  "landing-simulations": _landing_simulations,
  "landing-stats": _landing_stats,
  "labzero-main": _labzero_main,
  "landing-cards": _landing_cards,
  "landing-theory": _landing_theory,
  "landing-footer": _landing_footer,
  "auth-overlay": _auth_overlay,
})
