# Generated by Django 6.0 on 2026-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
