# Generated by Django 6.0.4 on 2026-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_assignment_file_assignment_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
