# Generated by Django 6.0.4 on 2026-04-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('central_atom', models.CharField(max_length=5)),
                ('real_angle', models.DecimalField(decimal_places=3, max_digits=6)),
                ('model_angle', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LonePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lone_pairs', to='lab_api.molecule')),
            ],
        ),
        migrations.CreateModel(
            name='AtomPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='lab_api.molecule')),
            ],
        ),
    ]
