# Generated by Django 6.0.4 on 2026-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0002_molecule_lonepair_atomposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='model_angle',
            field=models.CharField(help_text='The model Bond Angle in degrees (can be multiple values)', max_length=100),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='real_angle',
            field=models.CharField(help_text='The actual Bond Angle in degrees (can be multiple values)', max_length=100),
        ),
    ]
