# Generated by Django 6.0 on 2026-04-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0003_alter_molecule_model_angle_alter_molecule_real_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('target_class', models.JSONField(help_text="List of target classes, e.g., ['Class 11', 'Class 12']")),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_class', models.JSONField(help_text="List of target classes, e.g., ['Class 11']")),
                ('theory', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lab_api.subject')),
            ],
        ),
    ]
