# Generated by Django 6.0 on 2026-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0004_subject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, help_text="ID used by frontend (e.g., 'chemistry')", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, help_text="ID used by frontend (e.g., 'atomic_structure')", max_length=200, null=True),
        ),
    ]
