# Generated by Django 6.0 on 2026-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0005_subject_slug_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this topic appears (lower numbers appear first)'),
        ),
    ]
