# Generated by Django 6.0 on 2026-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0006_topic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
