# Generated by Django 6.0 on 2026-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0007_alter_topic_options_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon_color',
            field=models.CharField(default='text-indigo-500', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='theme',
            field=models.CharField(default='border-[var(--border-glass)]', max_length=100),
        ),
    ]
