# Generated by Django 6.0 on 2026-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0008_subject_icon_color_subject_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of appearance in the UI'),
        ),
    ]
