# Generated by Django 6.0 on 2026-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0009_subject_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_sort_method', models.CharField(choices=[('alpha', 'Alphabetical'), ('order', 'Custom Order')], default='order', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
