# Generated by Django 6.0 on 2026-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0010_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='model_url',
            field=models.URLField(blank=True, help_text='Link to .glb or .gltf model', max_length=500, null=True),
        ),
    ]
