# Generated by Django 6.0 on 2026-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0011_subject_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='model_url',
            field=models.CharField(blank=True, help_text='Link to .glb or .gltf model (e.g. /models/chem.glb)', max_length=500, null=True),
        ),
    ]
