# Generated by Django 6.0 on 2026-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0012_alter_subject_model_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='simulation_id',
            field=models.CharField(blank=True, help_text="ID for the 3D simulation (e.g., 'molecular_structure')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, help_text="Slug for URL (e.g., 'atomic-structure')", max_length=200, null=True),
        ),
    ]
